Allow fetching fresh route match
utopia-php/framework pull request #63
Opened 2022-07-18 07:11 UTC by abnegate

Allow re-matching route from request by passing fresh parameter

Supersedes #60

2022-07-25 07:52 UTC, eldadfux requested changes

2022-07-25 07:52 UTC, eldadfux commented on src/App.php
> +    public function match(Request $request, bool $fresh = false): ?Route
@abnegate let's add better documentation on the docblock for this new param.

2022-07-27 07:53 UTC, abnegate commented
@eldadfux Updated & test added

2022-07-30 09:55 UTC, eldadfux approved these changes

2022-07-30 09:55 UTC, merged